---
# Tasks for sysbench stuff

- name: Enable sysbench repo
  shell: >
    percona-release enable sysbench testing

- name: Install sysbench
  dnf:
    state: latest
    name: sysbench-1.1.0

- name: Check permissions of sysbench scripts
  copy: src=packer/sysbench/{{ item.src }} dest=/usr/local/bin/ mode={{ item.mode }} owner=rocky
  with_items:
    - { src: prepare_sysbench.sh, mode: "0755" }
    - { src: run_imdb_workload.sh, mode: "0755" }
    - { src: run_sysbench_oltp.sh, mode: "0755" }
